source 'https://github.com/CocoaPods/Specs'

xcodeproj 'OnkyoKit Tests'
workspace '../OnkyoKit'
# inhibit_all_warnings!

def import_pods
  # pod 'OCMock', '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'OnkyoKit', :path => '../'
end

# target :ios do
#   platform :ios, '7.0'
#   link_with 'iOS Tests'
#   import_pods
# end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end

target :network do
  platform :osx, '10.9'
  link_with 'OS X Network Tests'
  import_pods
end
